// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: imported/imported.proto

package imported

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImportedClient is the client API for Imported service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportedClient interface {
	GetRectangle(ctx context.Context, in *RectangleLocationRequest, opts ...grpc.CallOption) (*RectangleLocationResponse, error)
}

type importedClient struct {
	cc grpc.ClientConnInterface
}

func NewImportedClient(cc grpc.ClientConnInterface) ImportedClient {
	return &importedClient{cc}
}

func (c *importedClient) GetRectangle(ctx context.Context, in *RectangleLocationRequest, opts ...grpc.CallOption) (*RectangleLocationResponse, error) {
	out := new(RectangleLocationResponse)
	err := c.cc.Invoke(ctx, "/imported.Imported/GetRectangle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportedServer is the server API for Imported service.
// All implementations must embed UnimplementedImportedServer
// for forward compatibility
type ImportedServer interface {
	GetRectangle(context.Context, *RectangleLocationRequest) (*RectangleLocationResponse, error)
	mustEmbedUnimplementedImportedServer()
}

// UnimplementedImportedServer must be embedded to have forward compatible implementations.
type UnimplementedImportedServer struct {
}

func (UnimplementedImportedServer) GetRectangle(context.Context, *RectangleLocationRequest) (*RectangleLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRectangle not implemented")
}
func (UnimplementedImportedServer) mustEmbedUnimplementedImportedServer() {}

// UnsafeImportedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportedServer will
// result in compilation errors.
type UnsafeImportedServer interface {
	mustEmbedUnimplementedImportedServer()
}

func RegisterImportedServer(s grpc.ServiceRegistrar, srv ImportedServer) {
	s.RegisterService(&Imported_ServiceDesc, srv)
}

func _Imported_GetRectangle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RectangleLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportedServer).GetRectangle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imported.Imported/GetRectangle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportedServer).GetRectangle(ctx, req.(*RectangleLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Imported_ServiceDesc is the grpc.ServiceDesc for Imported service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Imported_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imported.Imported",
	HandlerType: (*ImportedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRectangle",
			Handler:    _Imported_GetRectangle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imported/imported.proto",
}
