// Copyright 2015 gRPC authors.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: primary/primary.proto

package primary

import (
	imported "github.com/pact-foundation/pact-go/v2/examples/grpc/imported"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One corner of the rectangle.
	Lo *imported.Point `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi *imported.Point `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_primary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_primary_primary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_primary_primary_proto_rawDescGZIP(), []int{0}
}

func (x *Rectangle) GetLo() *imported.Point {
	if x != nil {
		return x.Lo
	}
	return nil
}

func (x *Rectangle) GetHi() *imported.Point {
	if x != nil {
		return x.Hi
	}
	return nil
}

// A request payload to get a Rectangle.
type RectangleLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The width of the rectangle.
	X      int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width  int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Length int32 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *RectangleLocationRequest) Reset() {
	*x = RectangleLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_primary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RectangleLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectangleLocationRequest) ProtoMessage() {}

func (x *RectangleLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_primary_primary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectangleLocationRequest.ProtoReflect.Descriptor instead.
func (*RectangleLocationRequest) Descriptor() ([]byte, []int) {
	return file_primary_primary_proto_rawDescGZIP(), []int{1}
}

func (x *RectangleLocationRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RectangleLocationRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RectangleLocationRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RectangleLocationRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// A response payload containing a Rectangle.
type RectangleLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The location of the rectangle.
	Rectangle *Rectangle `protobuf:"bytes,1,opt,name=rectangle,proto3" json:"rectangle,omitempty"`
}

func (x *RectangleLocationResponse) Reset() {
	*x = RectangleLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primary_primary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RectangleLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectangleLocationResponse) ProtoMessage() {}

func (x *RectangleLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_primary_primary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectangleLocationResponse.ProtoReflect.Descriptor instead.
func (*RectangleLocationResponse) Descriptor() ([]byte, []int) {
	return file_primary_primary_proto_rawDescGZIP(), []int{2}
}

func (x *RectangleLocationResponse) GetRectangle() *Rectangle {
	if x != nil {
		return x.Rectangle
	}
	return nil
}

var File_primary_primary_proto protoreflect.FileDescriptor

var file_primary_primary_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x1a, 0x17, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x09, 0x52, 0x65, 0x63,
	0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x02, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x02, 0x6c, 0x6f, 0x12, 0x1f, 0x0a, 0x02, 0x68, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x02, 0x68, 0x69, 0x22, 0x64, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x74,
	0x61, 0x6e, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x4d,
	0x0a, 0x19, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x52, 0x09, 0x72, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x32, 0x62, 0x0a,
	0x07, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x57, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x67, 0x0a, 0x18, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x42, 0x0c, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61, 0x63, 0x74, 0x2d, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x63, 0x74, 0x2d, 0x67,
	0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_primary_primary_proto_rawDescOnce sync.Once
	file_primary_primary_proto_rawDescData = file_primary_primary_proto_rawDesc
)

func file_primary_primary_proto_rawDescGZIP() []byte {
	file_primary_primary_proto_rawDescOnce.Do(func() {
		file_primary_primary_proto_rawDescData = protoimpl.X.CompressGZIP(file_primary_primary_proto_rawDescData)
	})
	return file_primary_primary_proto_rawDescData
}

var file_primary_primary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_primary_primary_proto_goTypes = []interface{}{
	(*Rectangle)(nil),                 // 0: primary.Rectangle
	(*RectangleLocationRequest)(nil),  // 1: primary.RectangleLocationRequest
	(*RectangleLocationResponse)(nil), // 2: primary.RectangleLocationResponse
	(*imported.Point)(nil),            // 3: imported.Point
}
var file_primary_primary_proto_depIdxs = []int32{
	3, // 0: primary.Rectangle.lo:type_name -> imported.Point
	3, // 1: primary.Rectangle.hi:type_name -> imported.Point
	0, // 2: primary.RectangleLocationResponse.rectangle:type_name -> primary.Rectangle
	1, // 3: primary.Primary.GetRectangle:input_type -> primary.RectangleLocationRequest
	2, // 4: primary.Primary.GetRectangle:output_type -> primary.RectangleLocationResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_primary_primary_proto_init() }
func file_primary_primary_proto_init() {
	if File_primary_primary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primary_primary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rectangle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primary_primary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RectangleLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primary_primary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RectangleLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primary_primary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primary_primary_proto_goTypes,
		DependencyIndexes: file_primary_primary_proto_depIdxs,
		MessageInfos:      file_primary_primary_proto_msgTypes,
	}.Build()
	File_primary_primary_proto = out.File
	file_primary_primary_proto_rawDesc = nil
	file_primary_primary_proto_goTypes = nil
	file_primary_primary_proto_depIdxs = nil
}
